config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'

  resources :tasks
  
  get "signup", to: "users#new"
  resources :users, only: [:new, :create]
  
  get "login", to:"sessions#new"
  post "login", to:"sessions#create"
  delete "logout", to:"sessions#destroy"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user  #, optional: true
  
  validates :status, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  
  private
  
  def require_user_logged_in
    unless logged_in?
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email,password)
      flash[:success] = "ログイン成功"
      redirect_to root_url
    else
      flash.now[:danger] = "ログイン失敗"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] ="ログアウト完了"
    redirect_to root_url
  end
  
  private
  
  def login(email,password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @tasks = current_user.tasks.order("created_at DESC").page(params[:page])
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    # @task = Task.new(task_params)
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = 'タスクが正常に登録されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクが登録されませんでした'
      render :new
    end
  end

  def edit
  end

  def update

    if @task.update(task_params)
      flash[:success] = 'タスクは正常に更新されました'
      redirect_to @task
    else
      flash.now[:danger] = 'タスクは更新されませんでした'
      render :edit
    end
  end

  def destroy
    @task.destroy

    flash[:success] = 'タスクは正常に削除されました'
    redirect_to tasks_url
  end
  
  
  private
  
  # def set_task
  # @task = Task.find(params[:id])
  # end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to root_url
    end
  end
  
  
  def task_params
    params.require(:task).permit(:content, :status)
  end

  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = "登録完了"
      redirect_to root_url
    else
      flash.now[:danger] = "登録失敗"
      render :new
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div><%= message %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to 'Logout', logout_path, method: :delete %>
    <% end %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

  <% if task.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <%= f.label :status, 'ステータス' %>
  <%= f.text_field :status %>
 
  <%= f.label :content, 'タスク' %>
  <%= f.text_field :content %>

  <%= f.submit '登録' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>id: <%= @task.id %> - 編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.id,task %> : <%= task.status %> &gt; <%= task.content %></li>
  <% end %>
</ul>

<%= link_to '新規タスク作成', new_task_path %>

app/views/tasks/new.html.erb
<h1>作成ページ</h1>

<%= render "form", task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id: <%= @task.id %> - 詳細ページ</h1>

<p><%= @task.status %></p>
<p><%= @task.content %></p>

<%= link_to "一覧",tasks_path %>
<%= link_to '編集する', edit_task_path(@task) %>
<%= link_to '削除する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div>
  <%= form_with(model: @user, local:true) do |f| %>
    <%= render "layouts/error_messages", model: f.object %>
  
    <div>
      <%= f.label :name, "Name" %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email, "Email" %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
    </div>
    
    <%= f.submit "Sign up" %>

  <% end %>
    
</div>